Modifiers cannot be applied multiple times
leonardt/hwtypes pull request #112
Opened 2020-01-12 16:25 UTC by rdaly525

Adds a check to wrap_modifiers to verify that two of the same modifiers are not applied.
This check is probably best done in _ModifierMeta.__call__ as currently it returns a cryptic error message

2020-01-13 16:55 UTC, cdonovick requested changes
White space after commas.

TypeError not ValueError

2020-01-13 17:09 UTC, rdaly525 commented
Fixed

2020-01-14 22:28 UTC, cdonovick approved these changes
Good modulo simple whitespace fix

2020-01-14 22:28 UTC, cdonovick commented on hwtypes/modifiers.py
> +    ModType = _ModifierMeta(name, (AbstractModifier, ), {})
No space after trailing comma,

2020-01-16 20:08 UTC, merged