Add type string to hash for uniqueness
leonardt/hwtypes pull request #140
Opened 2020-09-14 19:02 UTC by leonardt

This way BitVector/SIntVector/UIntVector hash to different values,
avoiding collisions (this becomes a problem in magma's cacheing for
generator arguments, because UIntVector and SIntVector of the same
underlying value will hash to the same value, but we actually want them
to dispatch to different generators since one will generate UInt and the
other SInt for the interface types)

2020-09-14 20:44 UTC, rsetaluri approved these changes
A few comments:

(A) I think this change itself is fine, as long as no one is depending on the opposite condition of the hash, i.e. no other code assumes `hash(T1(x)) = hash(T2(x)) = hash(x)` (where `T1, T2 \in {UInt[n], SInt[m]} forall n, m`). Seems plausible that external code uses this since the hash is specifically overriden.

(B) Separately, I presume this change is to support the case of using the magma register generator like `Register(T = None, init = UInt(...))`? In this case `T` is kind of a shadow parameter inferred from `init`. I actually think this is a shortcoming of the generator interface, wherein we cache the `__init__` arguments themselves, but there may be parameters necessary for unique caching derived inside the `__init__`.

As long as (A) is confirmed (i.e. this change is safe to external users), then I think this is fine to unblock. But I think (B) is still a valid issue, and I will create a separate issue to track it.

2020-09-15 20:07 UTC, leonardt commented
I'm not sure about (A)

For (B) one option to avoid this issue is to have the parameter hashing logic be BV/UInt/SInt aware and hash them differently (e.g. using the logic in this change).  This would then avoid (A) and we can close this rather than having a breaking interface change.

I thought about this a bit more and I'm not sure what I'd do from scratch.  From one perspective, having them hash to the same value isn't unreasonable, but on the other hand, the user could always do something like "int(val)" to get this behavior.

2021-01-27 22:46 UTC, cdonovick requested changes
Sorry just seeing this now I guess I missed it.  I'm fine with the general idea.

2021-01-27 22:46 UTC, cdonovick commented on hwtypes/bit_vector.py
> +        return hash(f"{type(self)}{self._value}")
I would prefer `hash((type(self), self._value))`

2021-02-12 01:36 UTC, cdonovick approved these changes

2021-02-12 15:27 UTC, merged